### ISSUE TITLE
Marlin support Monoprice Ultimate / Wanhao Duplicator-6

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [norpchen/Ultimaker2Marlin#7]
Lars, hello.

1) I am trying to see if people (like you) interested in 
Monoprice Ultimate / Wanhao Duplicator-6
still might come together under original Marlin umbrella:
https://github.com/MarlinFirmware/Marlin/issues/6818

2) I would also appreciate your thoughts on 
Marlin vs Ultimaker2Marlin difference, if you had chance to work with both.

Thank you.

**Comment by norpchen** [comment]
Not sure what you mean about the Monoprice Ultimate / Wanhao Duplicator-6 ?   I don't know anything about those machines. 

I have worked with both Marlin and Ultimaker2Marlin -- most of the changes for the UM2 branch of Marlin are in the menu and LCD areas.  The core areas like motion control, gcode processing, temp control, etc. are mostly unchanged (although the UM2 hasn't resynced with the main Marlin branch since it forked, so it doesn't have any of the newer features of Marlin).   The UM2 fork is mostly just a customization to add menus, some smarts to SD card printing, and interface & display control specific to the UM2 hardware. 

 I haven't worked on the Marlin code for several years now, but it really hasn't changed very much at it's core.  It's very much showing it's age and  overstretched in trying to accommodate all possible configurations, making an #ifdef nightmare.

**Comment by Andrei-Pozolotin** [comment]
thank you
